SimBotUltraSumarizer/Controllers/EthTrackerWalletsController.cs
using Microsoft.AspNetCore.Mvc;
using SimBotUltraSummarizer.ViewModels;
using SimBotUltraSummarizerDb.Dal;

namespace SimBotUltraSummarizer.Controllers
{
    public class EthTrackerWalletsController : Controller
    {
        public IActionResult Search(EthTrackerWalletsSearchFormModel searchForm)
        {
            var model = this.ExecuteSearch(searchForm);

            return this.View(model);
        }

        protected EthTrackerWalletsSearchModel ExecuteSearch(EthTrackerWalletsSearchFormModel searchForm)
        {
            searchForm.SetDefaultSort("etw.id", sortDesc: true);
            searchForm.EthTrackerTypes = EthTrackerTypes.GetAll();

            var response = EthTrackerWallets.Search(searchForm.ToSearchRequest());

            EthTrackerWallets.LoadTypes(response.Records);

            var model = new EthTrackerWalletsSearchModel(searchForm)
            {
                Response = response,
                EthTrackerWalletSignalsCountDict = EthTrackerSignals.GetWalletSignalsCount(response.Records.Select(r => r.Address))
            };

            return model;
        }
    }
}

SimBotUltraSumarizer/Controllers/SignalsController.cs
using Microsoft.AspNetCore.Mvc;
using SimBotUltraSummarizer.ViewModels;
using SimBotUltraSummarizerDb.Dal;

namespace SimBotUltraSummarizer.Controllers
{
    public class SignalsController : Controller
    {
        public IActionResult Search(SignalsSearchFormModel searchForm)
        {
            var model = this.ExecuteSearch(searchForm);

            return this.View(model);
        }


        protected SignalsSearchModel ExecuteSearch(SignalsSearchFormModel searchForm)
        {
            searchForm.SetDefaultSort("s.edited_at", sortDesc: true);
            searchForm.EthTrackerWallets = EthTrackerWallets.GetAll();
            searchForm.Filters = Filters.GetAll();

            var response = Signals.Search(searchForm.ToSearchRequest());

            Signals.LoadSignalData(response.Records);
            Signals.LoadHypeSignals(response.Records);
            Signals.LoadITokenSignals(response.Records);
            Signals.LoadEthTrackerSignals(response.Records);
            EthTrackerSignals.LoadWallets(response.Records.SelectMany(r => r.EthTrackerSignals));
            EthTrackerWallets.LoadTypes(response.Records.SelectMany(r => r.EthTrackerSignals).Select(x => x.EthTrackerWallet));

            var model = new SignalsSearchModel(searchForm)
            {
                Response = response
            };

            return model;
        }
    }
}

SimBotUltraSumarizer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SimBotUltraSummarizer</title>
    <link href="/lib/bootstrap-5.3.1-dist/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SimBotUltraSummarizer.styles.css" asp-append-version="true" />
    <link href="~/fonts/fontawesome-6.5.1/css/all.min.css" rel="stylesheet" />
</head>
<script src="~/lib/jquery-3.6.0/jquery-3.6.0.min.js"></script>


<body>
    <header id="header" class="mb-3">
        <nav class="navbar navbar-expand-lg navbar-light bg-light mb-2">
            <div class="container-fluid">
                <a class="navbar-brand" href="@Url.Action("Search", "Signals", new { area = string.Empty })"><strong id="app-title">AlphaSync</strong></a>
                <ul class="navbar-nav me-auto"></ul>
                <ul class="navbar-nav ">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Search", "Signals", new { area = string.Empty })">Sim Bot Signals</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Search", "EthTrackerWallets", new { area = string.Empty })"> Wallets</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="@(ViewBag.FullPageWidth == true ? "container-fluid" : "container")" ">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AlphaSync - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="/js/jquery-ajax-json.js?v=@ViewBag.BuildVersion"></script>

    <script src="/lib/popper-2.11.8/popper.min.js"></script>
    <script src="/lib/bootstrap-5.3.1-dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ajax-json.js"></script>
    <script src="~/lib/vuejs-3.2.47/vue.global.js"></script>
    <link href="~/lib/flatpickr-4.6.13/flatpickr.min.css" rel="stylesheet" />
    <script src="~/lib/flatpickr-4.6.13/flatpickr.min.js"></script>
    <script src="~/lib/dayjs-1.11.5/dayjs.min.js"></script>
    <script src="~/lib/dayjs-1.11.5/plugins/utc.min.js"></script>
    <script src="~/lib/dayjs-1.11.5/plugins/duration.min.js"></script>
    <script src="~/lib/highcharts-11.1.0/highcharts.js"></script>
    <script src="~/lib/highcharts-11.1.0/modules/exporting.js"></script>
    <script src="~/lib/highcharts-11.1.0/modules/no-data-to-display.js"></script>
    <script src="~/lib/highcharts-11.1.0/modules/sankey.js"></script>
    <script src="~/lib/highcharts-11.1.0/modules/accessibility.js"></script>
    <script src="~/lib/numeral-js-2.0.6/min/numeral.min.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

SimBotUltraSumarizer/Views/Shared/_PagedListPagerAndOptionsPartial.cshtml
@model SimBotUltraSummarizer.ViewModels.Pager

@{ 
    var pageParam = "page";
    var queryString = this.Context.Request.Query.ToNameValueCollection();
}

<div class="row pagination-and-options-container @(Model.CssClass)">

    <div class="col-auto mb-2">
        <ul class="pagination pagination-sm my-0">
            <li class="page-item @(Model.Page > 1 ? "" : "disabled d-none")">
                <a href="@(Model.Page > 1 ? Url.Action(Url.CurrentAction(), null, queryString: queryString.AddOrSet(pageParam, 1.ToString())) : "javascript:void(0)")" class="page-link"><i class="fas fa-angle-double-left"></i></a>
            </li>

            <li class="page-item @(Model.Page > 1 ? "" : "disabled d-none")">
                <a href="@(Model.Page > 1 ? Url.Action(Url.CurrentAction(), null, queryString: queryString.AddOrSet(pageParam, (Model.Page - 1).ToString())) : "javascript:void(0)")" class="page-link"><i class="fas fa-angle-left"></i></a>
            </li>

            @if (Model.DisplayedPages.First() > 1)
            {
                <li class="page-item disabled d-none d-md-inline-block">
                    <a class="border-top-0 border-bottom-0 page-link bg-transparent" href="javascript:void(0)">...</a>
                </li>
            }

            @foreach (var page in Model.DisplayedPages)
            {
                <li class="page-item @(Model.Page == page ? "active" : "") @(Math.Abs(Model.Page - page) > (Model.Page == 1 || Model.Page == Model.PagesCount ? 2 : 1) ? "d-none d-md-inline-block" : "")">
                    <a href="@Url.Action(Url.CurrentAction(), null, queryString: queryString.AddOrSet(pageParam, page.ToString()))" class="page-link">@(page)</a>
                </li>
            }

            @if (Model.DisplayedPages.Last() < Model.PagesCount)
            {
                <li class="page-item disabled d-none d-md-inline-block">
                    <a class="border-top-0 border-bottom-0 page-link bg-transparent" href="javascript:void(0)">...</a>
                </li>
            }

            <li class="page-item @(Model.Page < Model.PagesCount ? "" : "disabled d-none")">
                <a href="@(Model.Page < Model.PagesCount ? Url.Action(Url.CurrentAction(), null, queryString: queryString.AddOrSet(pageParam, (Model.Page + 1).ToString())) : "javascript:void(0)")" class="page-link"><i class="fas fa-angle-right"></i></a>
            </li>

            <li class="page-item @(Model.Page < Model.PagesCount ? "" : "disabled d-none")">                
                <a href="@(Model.Page < Model.PagesCount ? Url.Action(Url.CurrentAction(), null, queryString: queryString.AddOrSet(pageParam, (Model.PagesCount).ToString())) : "javascript:void(0)")" class="page-link"><i class="fas fa-angle-double-right"></i></a>
            </li>
        </ul>
    </div>

    @if (Model.PageSizes.HasItems())
    {        
        <div class="col-auto mb-2 pl-md-0">
            <div class="dropdown">
                <button type="button" class="btn btn-page-size btn-no-outline btn-sm dropdown-toggle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Show @Model.PageSize <span class="caret"></span>
                </button>

                <div class="dropdown-menu mb-2">
                    @foreach (var item in Model.PageSizes)
                    {
                        <a class="dropdown-item" href="@Url.Action(Url.CurrentAction(), null, queryString: this.Context.Request.Query.ToNameValueCollection().RemoveIfExists("page", ignoreCase: true).AddOrSet("rowCount", item.ToString(), ignoreCase: true))">@item</a>
                    }
                </div>
            </div>
        </div>
    }

    @if (Model.ShowCreateButton)
    {
        <div class="col-auto mb-2">
            @Html.ActionLink("Create", "Create", Model.CreateButtonRouteValues, new { @class = "btn btn-sm btn-info" })
        </div>
    }
</div>