SimBotUltraSumarizer/Controllers/Api/SignalsApiController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using SimBotSummarizer.Helpers.Extensions;
using SimBotTelegram.Api.Ver1;
using SimBotUltraSummarizerDb.Dal;
using SimBotUltraSummarizerDb.Models;

namespace SimBotUltraSummarizer.Controllers.Api
{
    [ApiController]
    [Route("/api/Signals/[action]")]
    public class SignalsApiController : ControllerBase
    {
        private readonly SimBotTelegramApi _simBotTelegramApi;
        private readonly Microsoft.Extensions.Hosting.IHostingEnvironment _hostingEnvironment;
        public SignalsApiController(SimBotTelegramApi simBotTelegramApi, Microsoft.Extensions.Hosting.IHostingEnvironment hostingEnvironment)
        {
            this._simBotTelegramApi = simBotTelegramApi;
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult UpdateScam(uint id, bool isScam)
        {
            var signal = Signals.GetById(id);

            if (signal == null) { throw new Exception(); }

            signal.IsScam = isScam;

            Signals.Update(signal);

            return this.Ok(new {});
        }

        [AllowAnonymous]
        public IActionResult GetSignals()
        {
            var lastDateSimBot = SignalDatas.GetLastDate();
            var lastDateHypeBot = HypeSignals.GetLastDate();
            var lastDateIToken = ITokens.GetLastDate();
            var lastDateEthTracker1 = EthTrackerSignals.GetLastDate(EthTrackerTypes.MainAccount);
            var lastDateEthTracker2 = EthTrackerSignals.GetLastDate(EthTrackerTypes.SecondAccount);

            var signals = _simBotTelegramApi.GetMessages(lastDateSimBot, lastDateHypeBot, lastDateIToken, lastDateEthTracker1, lastDateEthTracker2);

            this.InsertSimBotSignals(signals.SimBotMessasges);
            this.InsertHypeSignals(signals.HypeMessages);
            this.InsertITokenSignals(signals.ITokenMessages);
            this.InsertEthTrackerSignals(signals.EthTrackerMessages1, EthTrackerTypes.MainAccount);
            this.InsertEthTrackerSignals(signals.EthTrackerMessages2, EthTrackerTypes.SecondAccount);

            return this.Ok(new { });
        }

        public IActionResult GetSimBotSignals()
        {
            var lastDate = SignalDatas.GetLastDate();

            var response = _simBotTelegramApi.GetSimBotMessages(lastDate);

            this.InsertSimBotSignals(response);

            return this.Ok();
        }

        public IActionResult GetHypeSignals()
        {
            var lastDate = HypeSignals.GetLastDate();

            var response = _simBotTelegramApi.GetHypeMessages(lastDate);

            this.InsertHypeSignals(response);

            return this.Ok();
        }

        public IActionResult GetITokenSignals()
        {
            var lastDate = ITokens.GetLastDate();

            var response = _simBotTelegramApi.GetITokenMessages(lastDate);

            this.InsertITokenSignals(response);

            return this.Ok();
        }

        public IActionResult LoadSimBotSignals()
        {
            var signals = this.LoadJson<List<SimBotTelegram.Api.Ver1.Models.SimBotMessasge>>("response.json");

            this.InsertSimBotSignals(signals);

            return this.Ok(new { });
        }

        public IActionResult LoadHypeSignals()
        {
            var hypeSignals = this.LoadJson<List<SimBotTelegram.Api.Ver1.Models.HypeMessage>>("response_hype.json");

            this.InsertHypeSignals(hypeSignals);

            return this.Ok(new { });
        }

        public IActionResult LoadITokenSignals()
        {
            var itokenSignals = this.LoadJson<List<SimBotTelegram.Api.Ver1.Models.ITokenMessage>>("response_itoken.json");

            this.InsertITokenSignals(itokenSignals);

            return this.Ok(new { });
        }

        private void InsertSimBotSignals(List<SimBotTelegram.Api.Ver1.Models.SimBotMessasge> response)
        {
            if (!response.HasItems()) { return; }

            var addresses = response.Select(s => s.Address);
            var signalsDict = Signals.GetByAddresses(addresses).ToDictionary(x => x.Address, x => x.Id);

            foreach (var item in response)
            {
                if (!signalsDict.ContainsKey(item.Address.Trim()))
                {
                    var signal = new Signal
                    {
                        Name = item.Name,
                        Address = item.Address,
                        Pair = item.Pair,
                    };

                    Signals.Insert(signal);

                    signalsDict.Add(signal.Address, signal.Id);
                }

                if (item.SignalData.HasItems())
                {
                    foreach (var item2 in item.SignalData)
                    {
                        var signalData = new SignalData
                        {
                            SignalId = signalsDict[item.Address],
                            Address = item.Address,
                            MCap = item2.MCap,
                            TotalCalls = item2.TotalCalls,
                            SellTax = item2.SellTax,
                            BuyTax = item2.BuyTax,
                            Price = item2.Price,
                            Date = item2.Date
                        };

                        SignalDatas.Insert(signalData);
                    }
                }
            }
        }

        private void InsertHypeSignals(List<SimBotTelegram.Api.Ver1.Models.HypeMessage> response)
        {
            if (!response.HasItems()) { return; }

            foreach (var item in response)
            {
                var hypeSingal = new HypeSignal
                {
                    Address = item.Address,
                    MCap = item.MCap,
                    AlarmType = item.AlarmType,
                    Date = item.Date
                };

                HypeSignals.Insert(hypeSingal);
            }
        }

        private void InsertITokenSignals(List<SimBotTelegram.Api.Ver1.Models.ITokenMessage> response)
        {
            if (!response.HasItems()) { return; }

            foreach (var item in response)
            {
                var itokenMessage = new IToken
                {
                    Address = item.Address,
                    Scan = item.Scan,
                    Date = item.Date
                };

                ITokens.Insert(itokenMessage);
            }
        }

        private void InsertEthTrackerSignals(List<SimBotTelegram.Api.Ver1.Models.EthTrackerMessage> response, uint ethTrackerTypeId)
        {
            if (!response.HasItems()) { return; }

            foreach (var item in response)
            {
                var walletData = item.WalletData.Split("-");
                var walletName = walletData[0].Trim();
                var walletAddress = walletData.Length > 1 ? walletData[1].Trim() : null;
                var ethTrackerWallet = EthTrackerWallets.Get(walletAddress, walletName, ethTrackerTypeId);

                if (ethTrackerWallet == null)
                {
                    ethTrackerWallet = new EthTrackerWallet
                    {
                        EthTrackerTypeId = ethTrackerTypeId,
                        Name = walletName,
                        Address = walletAddress,
                        IsActive = true
                    };

                    EthTrackerWallets.Insert(ethTrackerWallet);
                }

                var ethTrackerSignal = new EthTrackerSignal
                {
                    EthTrackerWalletId = ethTrackerWallet.Id,
                    Address = item.Address,
                    Date = item.Date
                };

                EthTrackerSignals.Insert(ethTrackerSignal);
            }
        }

        private T LoadJson<T>(string fileName)
        {
            var rootPath = _hostingEnvironment.ContentRootPath;

            var fullPath = Path.Combine(rootPath, fileName);

            var jsonData = System.IO.File.ReadAllText(fullPath);

            if (string.IsNullOrWhiteSpace(jsonData)) { return default; }

            return JsonConvert.DeserializeObject<T>(jsonData);
        }
    }
}

SimBotUltraSumarizer/Controllers/EthTrackerWalletsController.cs
using Microsoft.AspNetCore.Mvc;
using SimBotUltraSummarizer.ViewModels;
using SimBotUltraSummarizerDb.Dal;

namespace SimBotUltraSummarizer.Controllers
{
    public class EthTrackerWalletsController : Controller
    {
        public IActionResult Search(EthTrackerWalletsSearchFormModel searchForm)
        {
            var model = this.ExecuteSearch(searchForm);

            return this.View(model);
        }

        protected EthTrackerWalletsSearchModel ExecuteSearch(EthTrackerWalletsSearchFormModel searchForm)
        {
            searchForm.SetDefaultSort("etw.id", sortDesc: true);
            searchForm.EthTrackerTypes = EthTrackerTypes.GetAll();

            var response = EthTrackerWallets.Search(searchForm.ToSearchRequest());

            EthTrackerWallets.LoadTypes(response.Records);

            var model = new EthTrackerWalletsSearchModel(searchForm)
            {
                Response = response,
                EthTrackerWalletSignalsCountDict = EthTrackerSignals.GetWalletSignalsCount(response.Records.Select(r => r.Address))
            };

            return model;
        }
    }
}

SimBotUltraSumarizer/Controllers/SignalsController.cs
using Microsoft.AspNetCore.Mvc;
using SimBotUltraSummarizer.ViewModels;
using SimBotUltraSummarizerDb.Dal;

namespace SimBotUltraSummarizer.Controllers
{
    public class SignalsController : Controller
    {
        public IActionResult Search(SignalsSearchFormModel searchForm)
        {
            var model = this.ExecuteSearch(searchForm);

            return this.View(model);
        }


        protected SignalsSearchModel ExecuteSearch(SignalsSearchFormModel searchForm)
        {
            searchForm.SetDefaultSort("s.edited_at", sortDesc: true);
            searchForm.EthTrackerWallets = EthTrackerWallets.GetAll();
            searchForm.Filters = Filters.GetAll();

            var response = Signals.Search(searchForm.ToSearchRequest());

            Signals.LoadSignalData(response.Records);
            Signals.LoadHypeSignals(response.Records);
            Signals.LoadITokenSignals(response.Records);
            Signals.LoadEthTrackerSignals(response.Records);
            EthTrackerSignals.LoadWallets(response.Records.SelectMany(r => r.EthTrackerSignals));
            EthTrackerWallets.LoadTypes(response.Records.SelectMany(r => r.EthTrackerSignals).Select(x => x.EthTrackerWallet));

            var model = new SignalsSearchModel(searchForm)
            {
                Response = response
            };

            return model;
        }
    }
}

SimBotUltraSumarizer/Views/Signals/Search.cshtml
@model SimBotUltraSummarizer.ViewModels.SignalsSearchModel

@{
    ViewBag.Title = "Signals";
    ViewBag.FullPageWidth = true;
}

<script>
    $(document).ready(function () {
        $("#GetSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("GetSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });

        $("#GetSimBotSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("GetSimBotSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });

        $("#GetHypeSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("GetHypeSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });

        $("#GetITokenSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("GetITokenSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });

        $("#LoadSimBotSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("LoadSimBotSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });

        $("#LoadHypeSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("LoadHypeSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });

        $("#LoadITokenSignals").on("click", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("LoadITokenSignals", "SignalsApi"))),
                success: function (response, status, xhr) {
                    console.log(response)
                }
            });
        });
        
        $(".is-scam-checkbox").on("change", function () {
            $.ajaxGetJson({
                url: @Html.Raw(Json.Serialize(Url.Action("UpdateScam", "SignalsApi"))),
                data: { id: $(this).prop("id"), isScam: $(this).prop("checked") },
                success: function (response, status, xhr) {
                }
            });
        });
    });
</script>

<h1>@ViewBag.Title (@Model.Response.TotalRecords.ToString("N0"))</h1>

<partial name="SearchForm" model="Model.SearchForm" />
@* <button type="button" id="GetSignals">Get Signals</button>
<button type="button" id="GetSimBotSignals">Get Sim Bot Signals</button>
<button type="button" id="GetHypeSignals">Get Hype Signals</button>
<button type="button" id="GetITokenSignals">Get IToken Signals</button>
<button type="button" id="LoadSimBotSignals">Load Sim Bot Signals</button>
<button type="button" id="LoadHypeSignals">Load Hype Signals</button>
<button type="button" id="LoadITokenSignals">Load IToken Signals</button> *@

@if (!Model.Response.Records.HasItems())
{
    <div class="alert alert-success" role="alert">
        There are no signals.
    </div>

    return;
}

<div>
    <div class="d-inline-block me-4">
        <div class="mb-1">
            <partial name="_PagedListPagerAndOptionsPartial" model="Model.ToPager(showCreateButton: false)" />
        </div>
    </div>
</div>

<div class="row">
    @foreach (var signal in Model.Response.Records)
    {
        <div class="col-md-12">
            <div class="border rounded p-3 h-100">
                @* Main Info *@
                <div class="col-md-12">
                    <table class="table w-auto">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Address</th>
                                <th scope="col">Pair</th>
                                <th scope="col">Scam</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td style="word-break: break-all;">@signal.Name</td>
                                <td style="word-break: break-all;">@signal.Address</td>
                                <td style="word-break: break-all;">@signal.Pair</td>
                                <td>
                                    <input class="form-check-input is-scam-checkbox" type="checkbox" asp-for="@signal.IsScam" id="@signal.Id">
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                @* Dexscreener *@
                <div class="row">
                    <div class="col-md-12 col-sm-12 dex-container mb-3 ">
                        <iframe width="100%" height="100%" src="https://dexscreener.com/ethereum/@signal.Address?embed=1&theme=dark&trades=0"></iframe>
                    </div>

                    <hr>

                    @* Signals *@
                    <div class="col-md-8 col-sm-12" style="max-height: 400px; overflow:auto;">
                        <h4>Signal Data (@signal.SignalData.Count())</h4>
                        <table class="table w-auto">
                            <thead>
                                <tr>
                                    <th scope="col">MCap</th>
                                    <th scope="col">Total Calls</th>
                                    <th scope="col">Sell Tax</th>
                                    <th scope="col">Buy Tax</th>
                                    <th scope="col">Method Ids Launched</th>
                                    <th scope="col">Method Ids Rugged</th>
                                    <th scope="col">Method Ids %</th>
                                    <th scope="col">Functions Text Launched</th>
                                    <th scope="col">Functions Text Rugged</th>
                                    <th scope="col">Functions Text %</th>
                                    <th scope="col">Clog %</th>
                                    <th scope="col">Is Thrending</th>
                                    <th scope="col">Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var signalData in signal.SignalData)
                                {
                                    <tr>
                                        <td>@signalData.MCap</td>
                                        <td>@signalData.TotalCalls</td>
                                        <td>@signalData.SellTax?.ToString("N2")</td>
                                        <td>@signalData.BuyTax?.ToString("N2")</td>
                                        <td>@signalData.MethodIdsHashLaunched</td>
                                        <td>@signalData.MethodIdsHashRugged</td>
                                        <td>@signalData.MethodIdsPercent.ToString("P2")</td>
                                        <td>@signalData.FunctionsTextLaunched</td>
                                        <td>@signalData.FunctionsTextRugged</td>
                                        <td>@signalData.FunctionsTextPercent.ToString("P2")</td>
                                        <td>@(signalData.Clog.HasValue ? signalData.Clog.Value.ToString("P2") : "-")</td>
                                        <td>@(signalData.IsTrending ? "Yes" : "No")</td>
                                        <td>@signalData.Date.ToWebDateFormat(showTime: true)</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                    @*Eth Tracker, IToken, Hype Alarms*@
                    <div class="col-md-4 col-sm-12" style="max-height: 400px; overflow:auto;">
                        <h4>Eth Tracker Signals (@signal.EthTrackerSignals.Count())</h4>
                        @if (signal.EthTrackerSignals.Count() > 0)
                        {
                            <table class="table w-auto">
                                <thead>
                                    <tr>
                                        <th scope="col">Wallet Name</th>
                                        <th scope="col">Type</th>
                                        <th scope="col">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var x in signal.EthTrackerSignals)
                                    {
                                        <tr>
                                            <td><a asp-action="Search" asp-controller="EthTrackerWallets" asp-route-id="@x.EthTrackerWalletId">@x.EthTrackerWallet.Name</a></td>
                                            <td>@x.EthTrackerWallet.EthTrackerType.Name</td>
                                            <td>@x.Date.ToWebDateFormat(showTime: true)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <div class="alert alert-success" role="alert">
                                There are no Eth tracking signals for this token.
                            </div>
                        }
                        <h4>Hype Alarms (@signal.HypeSignals.Count())</h4>
                        @if (@signal.HypeSignals.Count() > 0)
                        {
                            <table class="table w-auto">
                                <thead>
                                    <tr>
                                        <th scope="col">MCap</th>
                                        <th scope="col">Alarm Type</th>
                                        <th scope="col">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var hypeSignal in signal.HypeSignals)
                                    {
                                        <tr>
                                            <td>@hypeSignal.MCap?.ToString("N2")</td>
                                            <td>@hypeSignal.AlarmType</td>
                                            <td>@hypeSignal.Date.ToWebDateFormat(showTime: true)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <div class="alert alert-success" role="alert">
                                There are no hype signals for this token.
                            </div>
                        }
                        <h4>IToken Signals (@signal.ITokens.Count())</h4>
                        @if (signal.ITokens.Count() > 0)
                        {
                            <table class="table w-auto">
                                <thead>
                                    <tr>
                                        <th scope="col">Scan</th>
                                        <th scope="col">Date</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var itoken in signal.ITokens)
                                    {
                                        <tr>
                                            <td>@itoken.Scan</td>
                                            <td>@itoken.Date.ToWebDateFormat(showTime: true)</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <div class="alert alert-success" role="alert">
                                There are no IToken signals for this token.
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    }
</div>

SimBotUltraSumarizer/Views/Signals/SearchForm.cshtml
@model SimBotUltraSummarizer.ViewModels.SignalsSearchFormModel

<form class="autosubmit mb-3" method="get">
    <div class="row">
        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="Keywords" class="form-label"></label>
            <input asp-for="Keywords" class="form-control" title="Search in name" data-bs-toggle="tooltip" data-bs-placement="bottom" />
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="Address" class="form-label"></label>
            <input asp-for="Address" class="form-control" title="Search in address" data-bs-toggle="tooltip" data-bs-placement="bottom" />
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="StartDate" class="form-label"></label>
            <input asp-for="StartDate" class="form-control" />
            <span asp-validation-for="StartDate"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="EndDate" class="form-label"></label>
            <input asp-for="EndDate" class="form-control" />
            <span asp-validation-for="EndDate"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="MCapFrom" class="form-label"></label>
            <input asp-for="MCapFrom" class="form-control" title="Search in name" data-bs-toggle="tooltip" data-bs-placement="bottom" />
            <span asp-validation-for="MCapFrom"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="MCapTo" class="form-label"></label>
            <input asp-for="MCapTo" class="form-control" title="Search in name" data-bs-toggle="tooltip" data-bs-placement="bottom" />
            <span asp-validation-for="MCapTo"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="TotalCallsFrom" class="form-label"></label>
            <input asp-for="TotalCallsFrom" class="form-control" title="Search in name" data-bs-toggle="tooltip" data-bs-placement="bottom" />
            <span asp-validation-for="TotalCallsFrom"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="TotalCallsTo" class="form-label"></label>
            <input asp-for="TotalCallsTo" class="form-control" title="Search in name" data-bs-toggle="tooltip" data-bs-placement="bottom" />
            <span asp-validation-for="TotalCallsTo"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="EthTrackerWalletId" class="form-label"></label>
            <select class="form-select" asp-for="EthTrackerWalletId">
                <option value="">--</option>
                @foreach (var item in Model.EthTrackerWallets)
                {
                    <option value="@item.Id">@item.Name - @item.EthTrackerType.Name</option>
                }
            </select>
            <span asp-validation-for="EthTrackerWalletId"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="HasHypeAlarmSignal" class="form-label"></label>
            <select class="form-select" asp-for="HasHypeAlarmSignal">
                <option value="">--</option>
                <option value="true">Yes</option>
                <option value="false">No</option>
            </select>
            <span asp-validation-for="HasHypeAlarmSignal"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="HasITokenSignal" class="form-label"></label>
            <select class="form-select" asp-for="HasITokenSignal">
                <option value="">--</option>
                <option value="true">Yes</option>
                <option value="false">No</option>
            </select>
            <span asp-validation-for="HasITokenSignal"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="HasEthTrackerSignal" class="form-label"></label>
            <select class="form-select" asp-for="HasEthTrackerSignal">
                <option value="">--</option>
                <option value="true">Yes</option>
                <option value="false">No</option>
            </select>
            <span asp-validation-for="HasEthTrackerSignal"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="IsScam" class="form-label"></label>
            <select class="form-select" asp-for="IsScam">
                <option value="">--</option>
                <option value="true">Yes</option>
                <option value="false">No</option>
            </select>
            <span asp-validation-for="IsScam"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label asp-for="UserId" class="form-label"></label>
            <select class="form-select" asp-for="UserId">
                <option value="">--</option>
                @foreach (var filter in Model.Filters)
                {
                    <option value="@filter.UserId">@(string.IsNullOrEmpty(filter.Name) ? filter.UserId : filter.Name)</option>
                }
            </select>
            <span asp-validation-for="UserId"></span>
        </div>

        <div class="col-sm-4 col-md-auto mb-2 pr-sm-0">
            <label class="h6">&nbsp;</label>
            <div>
                <a href="@Url.Action(action: null, controller: null)" class="btn btn btn-outline-info"><i class="fas fa-times"></i></a>
            </div>
        </div>
    </div>
</form>

<script>
    $(document).ready(function () {
        flatpickr("#StartDate", {
            dateFormat: 'Y-m-d H:i',
            locale: { 'firstDayOfWeek': 1 },
            allowInput: true,
            enableTime: true,
            time_24hr: true
        });

        flatpickr("#EndDate", {
            dateFormat: 'Y-m-d H:i',
            locale: { 'firstDayOfWeek': 1 },
            allowInput: true,
            enableTime: true,
            time_24hr: true
        });
    });
    $(function () {
        $('form.autosubmit select, form.autosubmit input[type="checkbox"], form.autosubmit input[type="text"], form.autosubmit input[type="number"], form.autosubmit input[type="time"], form.autosubmit input[type="datetime-local"]').on('change', function (event) {
            $(this).closest('form').submit();
        });
    });
</script>